#!/bin/bash
echo "hello"

function1()
{
    echo "call function 2 from function 1"
    function2
}


function2()

{

    echo "this is function2 "
}

function1

_()
{
    echo "the first arg is $1 , the second $2"
}

var1=10
var2=20
_ var1 var2


_ $1 $2


echo "####Arrays####"

arr[0]=20
arr[1]=30
echo -e "${arr[0]}\n${arr[1]}"

#another way to declare for array

declare -a arr1
#-a array
arr1=( 2 4 )
echo -e "${arr1[0]} \n ${arr1[1]} "

arr2=([0]="first" [1]="second" [7]="third")
echo -e "${arr2[0]} \n ${arr2[1]} \n ${arr2[7]} "


###########

arr3=( zero one two)
echo ${arr3[0]} #echo the first element
echo ${#arr3[0]} #echo the length of first element
echo ${#arr3[*]} #echo the size of array