#!/bin/bash
echo "hello"

function1()
{
    echo "call function 2 from function 1"
    function2
}


function2()

{

    echo "this is function2 "
}

function1

_()
{
    echo "the first arg is $1 , the second $2"
}

var1=10
var2=20
_ var1 var2


_ $1 $2


