#!/bin/bash
var=10
echo var
echo $var
# var is the name of variable
# $var is tha value of variable

unset var 
echo $var
#unset will set the variable to null

var1=44
((var2=var1<10?1:0))
echo $var2

#var2 value depends on var1 
# if var1 less than 10 then var2=1 else var2=0

echo "type in some value"
read var2
echo $var2

for var in 1 2 3
do
echo $var
done

NO_OF_ARGS=2
#THE NUMBER OF ARGUMENTS
E_BADARGS=85
E_UNREADABLE=86

#  $#  THE NUMBER OF COMMAND LINE ARGUMENTS
if [ $# -ne "$NO_OF_ARGS" ]
then
echo "Usage: 'basename $0' testFile1 testfile2"
#  #0  the name of the script
exit $E_BADARGS
 
fi 



